In [35]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [10]:
#Import des données
inc = pd.read_csv("/users/2024/ds2/119008303/Documents/Traitement images/Fiji.app/Summary of dupinc.csv")
led = pd.read_csv("/users/2024/ds2/119008303/Documents/Traitement images/Fiji.app/Summary of dupled.csv")

In [11]:
inc.head()

Slice  Count  Total Area  Average Size   %Area    Mean    Mode  Perim.  \
0     51    173     1165565      6737.370  88.926  28.816  28.844  59.095   
1     52    143     1153495      8066.399  88.005  28.844  28.860  71.560   
2     53    145     1182339      8154.062  90.205  28.857  28.897  66.548   
3     54    169     1128390      6676.864  86.089  28.757  28.787  80.932   
4     55    232     1118548      4821.328  85.338  28.840  28.897  60.429   

    Major  Minor  ...  Solidity   Feret   FeretX   FeretY  FeretAngle  \
0  15.273  8.115  ...     0.947  16.463  535.809  771.601     141.944   
1  15.910  9.120  ...     0.936  17.656  559.091  778.161     140.699   
2  16.303  9.376  ...     0.940  17.940  552.986  780.862     135.282   
3  17.920  8.185  ...     0.913  19.344  512.864  719.793     143.712   
4  14.197  6.254  ...     0.938  15.169  556.853  737.845     142.103   

   MinFeret      IntDen  Median   Skew   Kurt  
0     7.948  145241.769  28.890 -1.228  2.376  
1     8.999  175227.664  28.916 -0.831  0.274  
2     9.087  174020.138  28.917 -1.359  2.662  
3     8.254  145982.556  28.840 -0.983  0.514  
4     6.295  106055.948  28.918 -1.190  1.272  

[5 rows x 22 columns]

In [12]:
inc.columns

Index(['Slice', 'Count', 'Total Area', 'Average Size', '%Area', 'Mean', 'Mode',
       'Perim.', 'Major', 'Minor', 'Angle', 'Circ.', 'Solidity', 'Feret',
       'FeretX', 'FeretY', 'FeretAngle', 'MinFeret', 'IntDen', 'Median',
       'Skew', 'Kurt'],
      dtype='object')

In [13]:
led.head()

Slice  Count  Total Area  Average Size   %Area  Mean  Mode    Perim.  \
0     91      5     1271862    254372.400  97.035   255   255   925.043   
1     92      4     1271689    317922.250  97.022   255   255  1155.450   
2     93     22     1271331     57787.773  96.995   255   255   227.790   
3     94     11     1271196    115563.273  96.985   255   255   423.591   
4     95     14     1271962     90854.429  97.043   255   255   333.368   

     Major    Minor  ...  Solidity    Feret   FeretX   FeretY  FeretAngle  \
0  286.176  228.912  ...     0.994  329.747  590.400  338.800     132.581   
1  357.208  285.793  ...     0.957  411.743  594.250  389.750     148.935   
2   69.912   54.821  ...     0.891   81.031  831.091  541.500     132.103   
3  131.447  104.787  ...     0.958  151.394  801.455  491.091     128.671   
4  103.516   82.564  ...     0.971  119.217  820.286  489.286     136.683   

   MinFeret        IntDen  Median  Skew  Kurt  
0   205.800  6.486496e+07     255   NaN   NaN  
1   257.000  8.107017e+07     255   NaN   NaN  
2    50.420  1.473588e+07     255   NaN   NaN  
3    94.364  2.946863e+07     255   NaN   NaN  
4    74.286  2.316788e+07     255   NaN   NaN  

[5 rows x 22 columns]

In [14]:
led.columns

Index(['Slice', 'Count', 'Total Area', 'Average Size', '%Area', 'Mean', 'Mode',
       'Perim.', 'Major', 'Minor', 'Angle', 'Circ.', 'Solidity', 'Feret',
       'FeretX', 'FeretY', 'FeretAngle', 'MinFeret', 'IntDen', 'Median',
       'Skew', 'Kurt'],
      dtype='object')

In [21]:
#Création de X et Y:
X=pd.concat([inc,led])
Yled,Yinc=[9 for i in range(len(led))],[5 for i in range(len(inc))]
Y=np.concatenate((Yinc,Yled))
len(X)

16

In [57]:
Y

array([5, 5, 5, 5, 5, 5, 5, 5, 9, 9, 9, 9, 9, 9, 9, 9])

In [58]:
#On part de Mean, Feret et %Area comme features principales
Xt=pd.concat([X["Mean"],X["Feret"],X["%Area"]],axis=1)
Xt.head(10)

Mean    Feret   %Area
0   28.816   16.463  88.926
1   28.844   17.656  88.005
2   28.857   17.940  90.205
3   28.757   19.344  86.089
4   28.840   15.169  85.338
5   28.826   14.895  85.538
6   28.816   17.006  86.298
7   28.809   15.828  86.706
0  255.000  329.747  97.035
1  255.000  411.743  97.022

In [44]:
#SVM:
Xtrain,Xtest=train_test_split(Xt)
Ytrain,Ytest=train_test_split(Y)
svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm.fit(Xtrain, Ytrain)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [48]:
svm.score(Xtrain,Ytrain)

0.5833333333333334

In [46]:
svm.predict(Xtest)

array([9, 5, 5, 5])

In [47]:
Ytest

array([5, 9, 9, 5])

In [45]:
svm.score(Xtest,Ytest)

0.25

In [49]:
#Random Forest:
rf = RandomForestClassifier(n_estimators=20,max_depth=2, random_state=0)
rf.fit(Xtrain, Ytrain)

RandomForestClassifier(max_depth=2, n_estimators=20, random_state=0)

In [50]:
rf.score(Xtrain,Ytrain)

1.0

In [52]:
rf.predict(Xtest)

array([9, 5, 5, 5])

In [56]:
Xtest

Mean    Feret   %Area
3   28.757   19.344  86.089
1  255.000  411.743  97.022
7  255.000  547.891  97.070
0  255.000  329.747  97.035

In [53]:
Ytest

array([5, 9, 9, 5])

In [54]:
rf.score(Xtest,Ytest)

0.25

In [55]:
#Pas impressionnant dans les deux cas, tentons d'autres features

In [61]:
Xt1=pd.concat([X["Mean"],X["Feret"],X["Perim."]],axis=1)
Xt2=pd.concat([X["Mean"],X["Feret"],X["IntDen"]],axis=1)
Xt3=pd.concat([X["Major"],X["Feret"],X["%Area"]],axis=1)

In [62]:
#SVM:
Xtrain1,Xtest1=train_test_split(Xt1)
Xtrain2,Xtest2=train_test_split(Xt2)
Xtrain3,Xtest3=train_test_split(Xt3)
Ytrain,Ytest=train_test_split(Y)
svm1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm1.fit(Xtrain1, Ytrain)
svm2 = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm2.fit(Xtrain2, Ytrain)
svm3 = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svm3.fit(Xtrain3, Ytrain)
print(svm1.score(Xtest1,Ytest),svm2.score(Xtest2,Ytest),svm3.score(Xtest3,Ytest))

0.25 0.25 0.25


In [74]:
Xf=X.drop(columns=["Skew","Kurt"])
Xftrain,Xftest=train_test_split(Xt1)
Ytrain,Ytest=train_test_split(Y)
Xf.head()

Slice  Count  Total Area  Average Size   %Area    Mean    Mode  Perim.  \
0     51    173     1165565      6737.370  88.926  28.816  28.844  59.095   
1     52    143     1153495      8066.399  88.005  28.844  28.860  71.560   
2     53    145     1182339      8154.062  90.205  28.857  28.897  66.548   
3     54    169     1128390      6676.864  86.089  28.757  28.787  80.932   
4     55    232     1118548      4821.328  85.338  28.840  28.897  60.429   

    Major  Minor   Angle  Circ.  Solidity   Feret   FeretX   FeretY  \
0  15.273  8.115  29.670  0.719     0.947  16.463  535.809  771.601   
1  15.910  9.120  36.614  0.725     0.936  17.656  559.091  778.161   
2  16.303  9.376  31.688  0.739     0.940  17.940  552.986  780.862   
3  17.920  8.185  34.768  0.570     0.913  19.344  512.864  719.793   
4  14.197  6.254  31.048  0.663     0.938  15.169  556.853  737.845   

   FeretAngle  MinFeret      IntDen  Median  
0     141.944     7.948  145241.769  28.890  
1     140.699     8.999  175227.664  28.916  
2     135.282     9.087  174020.138  28.917  
3     143.712     8.254  145982.556  28.840  
4     142.103     6.295  106055.948  28.918

In [66]:
#SVM:
svmf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
svmf.fit(Xftrain, Ytrain)
svmf.score(Xftest,Ytest)

0.5

In [72]:
print(svmf.n_features_in_)
print(svmf.feature_names_in_)

3
['Mean' 'Feret' 'Perim.']


In [67]:
#Random Forest:
rff = RandomForestClassifier(n_estimators=20,max_depth=2, random_state=0)
rff.fit(Xftrain, Ytrain)
rff.score(Xftest,Ytest)

0.5

In [73]:
print(rff.n_features_in_)
print(rff.feature_names_in_)

3
['Mean' 'Feret' 'Perim.']
